### ISSUE TITLE
Laberda eske nofunciona

### ISSUE THREAD

**Issue by alex-deploys** [bonelessnugget/Programacion_Tema5_2#1]

**Comment by alex-deploys** [comment]
me decargue el 6 pero no va. arreglalo grasias un saludo

**Comment by alex-deploys** [comment]
ya lo arreglate?

**Comment by bonelessnugget** [comment]
No sha esta areglado master

**Comment by bonelessnugget** [comment]
Se puede esolver así: Un reloj atómico es un tipo de reloj que para alimentar su contador utiliza una frecuencia de resonancia atómica normal. Los primeros relojes atómicos tomaban su referencia de un máser.1​ Las mejores referencias atómicas de frecuencia (o relojes) modernas se basan en físicas más avanzadas, que involucran átomos fríos y fuentes atómicas. Las agencias de normas nacionales mantienen una exactitud de 10-9 segundos por día2​ y una precisión igual a la frecuencia del transmisor de la radio que bombea el máser.

Los relojes atómicos mantienen una escala de tiempo continua y estable, el Tiempo Atómico Internacional (TAI). Para uso cotidiano se difunde otra escala cronológica: el Tiempo Universal Coordinado (UTC). El UTC deriva del TAI, pero se sincroniza usando segundos de intercalación con el Tiempo Universal (UT1), el cual se basa en la transición día–noche según las observaciones astronómicas.

El primero se construyó en el Willard Frank Libby, de los EE. UU., en 1949, basándose en ideas acerca de un fenómeno extremadamente regular: la resonancia magnética molecular y atómica, de Isidor Isaac Rabi, Premio Nobel de Física,3​ aunque la precisión conseguida mediante amoníaco —molécula utilizada por el prototipo del National Institute of Standards and Technology (NIST)— no era muy superior a los estándares de la época, basados en osciladores de cuarzo.

Hoy los mejores patrones de frecuencia atómicos se basan en las propiedades físicas de las fuentes de emisión de cesio. El primer reloj atómico de cesio se construyó en 1955, en el National Physical Laboratory (NPL), en Inglaterra. Sus creadores fueron Louis Essen y John V.L Parry.4​

En el año 1967 los relojes atómicos basados en cesio habían conseguido fiabilidad suficiente como para que la Oficina Internacional de Pesas y Medidas eligiera la frecuencia de vibración atómica de los dispositivos creados y perfeccionados por Essen como nuevo patrón base para la definición de la unidad de tiempo físico. Según este patrón, un segundo se corresponde con 9 192 631 770 ciclos de la radiación asociada a la transición hiperfina desde el estado de reposo del isótopo de cesio 133: (133Cs).

La precisión alcanzada con este tipo de reloj atómico es tan elevada que admite únicamente un error de un segundo en 30 000 000 años. El reloj más preciso del mundo se diseña en el Observatorio de París, donde los actuales relojes atómicos tardarían 52 millones de años para desfasarse un segundo. El nuevo objetivo de la investigación francesa es aumentar ese plazo a 32 mil millones de años. El estándar actual de los relojes atómicos en activo permite el atraso de un segundo cada 3700 millones de años (NIST).
